site_name: 'Minha Documentação'
site_description: 'Documentação detalhada sobre o projeto'

theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'pink'

plugins:
  - search
  - meta-descriptions

nav:
  - Home: index.md
  - Introdução: introducao/inicio.md
  - Guia do Usuário: guia-do-usuario/configuracao.md
  - API:
    - Swagger UI: api/swagger-ui/index.html
    - OpenAPI (YAML): api/openapi.yaml